# Generated by Django 3.1.5 on 2021-02-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uid',
            new_name='id',
        ),
    ]
