# Generated by Django 3.1.5 on 2021-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210211_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('onhold', 'On Hold'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='new', max_length=20),
        ),
    ]
