# Generated by Django 3.1.5 on 2021-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='proposed', max_length=20)),
            ],
        ),
    ]
