# Generated by Django 3.1.5 on 2021-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_project_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='lastname',
        ),
    ]
