# Generated by Django 3.1.5 on 2021-01-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='firstname',
        ),
    ]
