export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";

export const EDIT_PROJECT_START = "EDIT_PROJECT_START";
export const EDIT_PROJECT_FAIL = "EDIT_PROJECT_FAIL";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";

export const CHECK_DATES = "CHECK_DATES";
export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";

export const CHANGE_USER_DATA = "CHANGE_USER_DATA";
export const TOOGLE_USER = "TOOGLE_USER";

export const APPLY_TITLE_DESC ="APPLY_TITLE_DESC";