export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const RESET_PASS = "RESET_PASS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const PROFILE_LIST_START = "PROFILE_LIST_START";
export const PROFILE_LIST_FAIL = "PROFILE_LIST_FAIL";
export const PROFILE_LIST_FINISH = "PROFILE_LIST_FINISH";
