export const GET_PROJECT_START = "GET_PROJECT_START";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";
export const GET_PROJECT_FINISH = "GET_PROJECT_FINISH";

export const PROJECT_DELETE_START = "PROJECT_DELETE_START";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";
export const PROJECT_DELETE_FINISH = "PROJECT_DELETE_FINISH";

export const PROJECT_ADD_START = "PROJECT_ADD_START";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_ADD_FINISH = "PROJECT_ADD_FINISH";
